// Hand-curated front-of-house types. The full machine-generated set lives in
// types.gen.ts (regenerated by `make typegen`). When something here diverges
// from the generated version, prefer the generated one and delete the local
// copy.

export type Severity = "critical" | "high" | "medium" | "low" | "info";
export type RegionTier = "sandbox" | "development" | "integration" | "production";
export type JobState = "pending" | "running" | "succeeded" | "failed" | "cancelled";
export type FindingDecision = "pending" | "accept" | "dismiss" | "auto_fixed";
export type AbendTier = "confirmed" | "probable" | "unfamiliar" | "unknown";

export interface User {
  user_id: string;
  email: string;
  display_name: string;
  roles: ("developer" | "reviewer" | "admin" | "service")[];
  shop: string;
}

export interface RegionListItem {
  name: string;
  tier: RegionTier;
  hlq: string;
}

export interface RegionDb2Config {
  subsystem_id: string;
  plan_collection: string;
  default_bind?: Record<string, string>;
}

export interface RegionProfile {
  name: string;
  tier: RegionTier;
  hlq: string;
  db2?: RegionDb2Config | null;
  racf_group?: string | null;
  scheduler_queue?: string | null;
  volser_pattern?: string | null;
  protected_resources?: string[];
  confidence_weight_overrides?: Record<string, number>;
}

export interface DiffField {
  path: string;
  a: unknown;
  b: unknown;
  kind: "value_change" | "added" | "removed";
}

export interface RegionDiffResponse {
  a: string;
  b: string;
  fields: DiffField[];
}

export interface Finding {
  id: string;
  rule_id: string;
  severity: Severity;
  description: string;
  details: Record<string, unknown>;
  auto_fix_available: boolean;
  decision: FindingDecision;
  created_at: string;
}

export interface ScanJob {
  job_id: string;
  state: JobState;
  jcl_name: string;
  target_region: string;
  created_at: string;
  finished_at: string | null;
  findings: Finding[];
}

export interface AbendEvent {
  event_id: string;
  abend_code: string | null;
  program: string | null;
  tier: AbendTier;
  created_at: string;
  summary: string | null;
}

export interface QueueItem {
  event_id: string;
  state: "pending_review" | "approved" | "rejected" | "auto_approved" | "expired";
  type: string;
  initiator: string;
  reviewers: string[];
  created_at: string;
  payload: Record<string, unknown>;
}

export interface ScoreBreakdown {
  total: number;
  components: {
    name: string;
    deduction: number;
    detail: string;
  }[];
}
